// --==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==
// -- DIFFERENT PLAYLISTS THAT THE BOT CAN DRAW FROM
// --==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==

var playlists = [

	{id: "chiptune", desc: "A small set of chiptune and keygen tracks for fuckin hackers", tracks: [
		{url:"https://www.youtube.com/watch?v=fL8XIeqWejc",title:"Maktone - Eargasm"},
		{url:"https://www.youtube.com/watch?v=HR41nFMREBE",title:"DiGERATi - Happy H. Christmas"},
		{url:"https://www.youtube.com/watch?v=04knWlZcUug",title:"8-BITChintendo - Lo-fi World"},
		{url:"https://www.youtube.com/watch?v=2fUmM4Lq4Ig",title:"DNA Groove - Pocket Tanks Theme"},
		{url:"https://www.youtube.com/watch?v=iadaXXBX_aY",title:"RELOADED - Dead Island Installer"},
		{url:"https://www.youtube.com/watch?v=nnKc08_cnro",title:"SKiDROW - Portal 2 Launcher"},
		{url:"https://www.youtube.com/watch?v=OcOJ8z5kmGA",title:"METROiD - Tomb Raider - Legend"},
		{url:"https://www.youtube.com/watch?v=TcTLFCz6thQ",title:"CRUDE - AVG Anti Spyware 7.5 propercrk"},
		{url:"https://www.youtube.com/watch?v=RFgXGw_kXpc",title:"Robocop (C64) - Title Theme"},
		{url:"https://www.youtube.com/watch?v=ZIJI83_oLaM",title:"RELOADED - Pro Evolution Soccer 2015 Installer"},
		{url:"https://www.youtube.com/watch?v=MViKOzrkzkc",title:"DYNAMITE - Winamp 5 0 RC8crk"},
		{url:"https://www.youtube.com/watch?v=bThTHiM8lkM",title:"PLAZA Installer Music - 2015 - November"},
		{url:"https://www.youtube.com/watch?v=Fcl1oEerizc",title:"CODEX (2015) Installer Music"},
		{url:"https://www.youtube.com/watch?v=dBY7Mvf95cs",title:"Justin Scharvona - predator-a-v2.mod"},
		{url:"https://www.youtube.com/watch?v=F5W2Wva4uRw",title:"Kalashnikov - nudity4.mod"},
		{url:"https://www.youtube.com/watch?v=5SzUu2GfeKE",title:"Jester - elysium.mod"},
		{url:"https://www.youtube.com/watch?v=fvhxgzjZF3I",title:"Rib - bombsoul.mod"},
		{url:"https://www.youtube.com/watch?v=TKqfeFHsYx8",title:"Civilization V Installer - SKIDROW"},
		{url:"https://www.youtube.com/watch?v=N5CNlMGcARA",title:"Insert No Coins - Razor1911"},
		{url:"https://www.youtube.com/watch?v=ocVej5jBBfE",title:"SKIDROW Launcher Music HD"},
		{url:"https://www.youtube.com/watch?v=2eCy3g0uDUs",title:"Razor1911 - Skyrim Installer"},
		{url:"https://www.youtube.com/watch?v=SDjxKrCrMos",title:"WaLMaRT Music - Morrowind GOTY"}
	]},
	
	{id: "chill", desc: "Just some general chill shit if you want to relax", tracks: [
		{url: "https://www.youtube.com/watch?v=o2Cm2WFGCYY", title: "Portabello Head"},
		{url: "https://www.youtube.com/watch?v=M6rJn_TEu5Y", title: "Portishead - Numb"},
		{url: "https://www.youtube.com/watch?v=g7gutsi1uT4", title: "Portishead - Sour Times"},
		{url: "https://www.youtube.com/watch?v=xDew2Ct40L4", title: "Nujabes - Luv Sic"},
		{url: "https://www.youtube.com/watch?v=jdQYzEc6wYw", title: "Nujabes - Luv Sic Pt. 2"},
		{url: "https://www.youtube.com/watch?v=t3baifH7bhI", title: "Portishead - Mysterons"},
		{url: "https://www.youtube.com/watch?v=SCZnEHG5fus", title: "Portishead - Biscuit"},
		{url: "https://www.youtube.com/watch?v=3KB54p8_wh8", title: "MC 900 Ft Jesus - The City Sleeps"},
		{url: "https://www.youtube.com/watch?v=1Zu854NIzdM", title: "MC 900 Ft Jesus - But If You Go"},
		{url: "https://www.youtube.com/watch?v=WVrTIdLqmjI", title: "Roku - Eclipse"},
		{url: "https://www.youtube.com/watch?v=snUk2SLuMBY", title: "said. - Sunflowers"},
		{url: "https://www.youtube.com/watch?v=QvHWaULIn6U", title: "Pigeondust - beat 8"},
		{url: "https://www.youtube.com/watch?v=jPvPsPk1r44", title: ".phase - Sudden Affection"},
		{url: "https://www.youtube.com/watch?v=encHVBJFcss", title: "driver - the eye of truth"},
		{url: "https://www.youtube.com/watch?v=vIgl1m5AM30", title: "Hooverphonic - 2 wicky"},
		{url: "https://www.youtube.com/watch?v=QPfh7qiIfm4", title: "Farid Bang - Teufelskreis"},
		{url: "https://www.youtube.com/watch?v=ptIcert_Ra8", title: "War - The World Is A Ghetto"},
		{url: "https://www.youtube.com/watch?v=vtPk5IUbdH0", title: "Eddy Grant - Electric Avenue"},
		{url: "https://www.youtube.com/watch?v=B7xai5u_tnk", title: "TheFatRat - Monody (feat. Laura Brehm)"},
		{url: "https://www.youtube.com/watch?v=9lyRI_M8ZXE", title: "Donkey Kong Country OST 20 - Ice Cave Chant"},
		{url: "https://www.youtube.com/watch?v=l-6QknAOsVo", title: "Nat King Col - Orange Colored Sky"},
		{url: "https://www.youtube.com/watch?v=rLUHuc3TqPs", title: "Odjbox - Bluebird (Bonus)"},
		{url: "https://www.youtube.com/watch?v=uPHmsEoLsL0", title: "Barry White - Love's Theme"},
		{url: "https://www.youtube.com/watch?v=upnrXooMh4s", title: "Phil Collins - You Can't Hurry Love"},
		{url: "https://www.youtube.com/watch?v=CX45pYvxDiA", title: "Mr. Sandman - The Chordettes"},
		{url: "https://www.youtube.com/watch?v=3aeQ3DmKU7A", title: "Cole Porter - Anything Goes"},
		{url: "https://www.youtube.com/watch?v=sLVawsuhlzY", title: "Black Sheep - The Choice Is Yours (Revisited)"},
		{url: "https://www.youtube.com/watch?v=4mNZAZgXYJo", title: "Super Mario World - Ending Theme"},
		{url: "https://www.youtube.com/watch?v=lrd8Ead93Yw", title: "Amy Winehouse - You Know I'm No Good"},
		{url: "https://www.youtube.com/watch?v=bDkqz5C62SM", title: "Doug E Fresh & Slick Rick-The Show"},
		{url: "https://www.youtube.com/watch?v=wTO0j49gYqY", title: "Heart of the Crypt"},
		{url: "https://www.youtube.com/watch?v=fxK7LES6xDA", title: "Fungal Funk"},
		{url: "https://www.youtube.com/watch?v=ghPbv7HiNzY", title: "Rhythmortis"},
		{url: "https://www.youtube.com/watch?v=S7-ITyrSCEU",title:"Jazz One - Still (Instrumental)"},
		{url: "https://www.youtube.com/watch?v=Agl1TgVfls0",title:"J Dilla - Life (Instrumental)"},
		{url: "https://www.youtube.com/watch?v=GFw03nxtvh0",title:"Atmosphere - Sunshine (Instrumental)"},
		{url: "https://www.youtube.com/watch?v=Y3-gT48_kYQ",title:"Clokworx - Mental Flux (Instrumental)"},
		{url: "https://www.youtube.com/watch?v=F2vmMck085A",title: "Destroy All Humans! - Little Star (Static Revenger Mix)"}
	]},
	
	{id: "cabaret", desc: "A bunch of edgy dark cabaret and shit, sounds like a circus", tracks: [
		{url: "https://www.youtube.com/watch?v=DC6UtsPa13o", title: "Voltaire - Brains!"},
		{url: "https://www.youtube.com/watch?v=5aO78NoCLe4", title: "Caravan of Thieves - Angels in Cages"},
		{url: "https://www.youtube.com/watch?v=lDp0VfKKxss", title: "Caravan of Thieves - Dr. Flynn"},
		{url: "https://www.youtube.com/watch?v=9ttEs6oyoao", title: "Caravan of Thieves - Rattlesnake"},
		{url: "https://www.youtube.com/watch?v=UBXl_r97d6Q", title: "Scarring Party - Anywhere"},
		{url: "https://www.youtube.com/watch?v=AxKEF8CczKo", title: "Dresden Dolls - Mandy Goes to Med School"},
		{url: "https://www.youtube.com/watch?v=50gak66Zgxs", title: "Anya Anastasia - Georgie Porgie"},
		{url: "https://www.youtube.com/watch?v=3e7P72Yiq0E", title: "Elizabeth & The Catapult - Sugar Covered Poison"},
		{url: "https://www.youtube.com/watch?v=A5u_CUBiB6E", title: "Curse In The Woods - Perfect Lawns"},
		{url: "https://www.youtube.com/watch?v=Cz4f5oBH7vk", title: "Bitter Ruin - Chewing Gum"},
		{url: "https://www.youtube.com/watch?v=4v04it-p8n8", title: "Pretty Balanced - Emyli"},
		{url: "https://www.youtube.com/watch?v=UjOwyJ4uZKM", title: "Pretty Balanced - Miriam"},
		{url: "https://www.youtube.com/watch?v=w1EZdx-2yzU", title: "Pretty Balanced - Cheap Drunk"},
		{url: "https://www.youtube.com/watch?v=c5E4W1G2S4I", title: "Emilie Autumn - Girls! Girls! Girls!"},
		{url: "https://www.youtube.com/watch?v=yyWwTUIVB9U", title: "Caravan Place - Bambous"},
		{url: "https://www.youtube.com/watch?v=BTeELC8A6-s", title: "Caravan Place - We Can Dance"},
		{url: "https://www.youtube.com/watch?v=X2gHTcKRo-I", title: "Caravan Place - Star Scat"},
		{url: "https://www.youtube.com/watch?v=ewo0m89By5A", title: "Caravan Place - Brotherswing"},
		{url: "https://www.youtube.com/watch?v=D1RLCgdBuaU", title: "Caravan Place - Suzy"},
		{url: "https://www.youtube.com/watch?v=Ki4PgLMoA2E", title: "This Way to the Egress - Turpentine"},
		{url: "https://www.youtube.com/watch?v=5kxKhF2pAE8", title: "Ray Childish - The Corpse Bride"},
		{url: "https://www.youtube.com/watch?v=24bu4axWD7k", title: "Amoree Lovell - Dark Town Sally"}
	]},
	
	{id: "fallout", desc: "A bunch of old-timey tracks inspired by Fallout and such", tracks: [
		{url:"https://www.youtube.com/watch?v=RuUbT_judgw",title:"Fox Boogie - Gerhard Trede"},
		{url:"https://www.youtube.com/watch?v=6OkQiVWIp_E",title:"Black Mountain Radio - Ain't That A Kick In The Head"},
		{url:"https://www.youtube.com/watch?v=AFJt_aaCVYA",title:"RNV - Blue Moon by Frank Sinatra"},
		{url:"https://www.youtube.com/watch?v=1DD_NCM_RJs",title:"FONV OST - Jingle Jangle Jingle"},
		{url:"https://www.youtube.com/watch?v=s4A3gCWfgpU",title:"FONV OST - Heartaches by The Numbers"},
		{url:"https://www.youtube.com/watch?v=9lrWx7-PiUM",title:"FONV Radio - In The Shadow of the Valley"},
		{url:"https://www.youtube.com/watch?v=4-E48jb14co",title:"Johnny Bond - Stars of the Midnight Ranger"},
		{url:"https://www.youtube.com/watch?v=1Qye2uNicbY",title:"FONV Radio - Happy Times"},
		{url:"https://www.youtube.com/watch?v=PZLwRL7xwRY",title:"FONV OST - Manhattan"},
		{url:"https://www.youtube.com/watch?v=DjuffT0mxIE",title:"Annette Hanshaw - My Sin (1929)"},
		{url:"https://www.youtube.com/watch?v=3aeQ3DmKU7A",title: "Cole Porter - Anything Goes"},
		{url:"https://www.youtube.com/watch?v=ww181bzE7Fg",title:"The Elegants - Little Star (1958)"},
		{url:"https://www.youtube.com/watch?v=lGXFVOc5I8Q",title:"The Big Bopper - Chantilly Lace"},
		{url:"https://www.youtube.com/watch?v=3rYoRaxgOE0",title:"Chordettes - Lollipop"}			
	]},
	
	{id: "caravan", desc: "Premade playlist of songs by Caravan Palace", tracks: [
		{url:"https://www.youtube.com/watch?v=8yozYOMkJEI",title:"Newbop"},
		{url:"https://www.youtube.com/watch?v=iDukPEAZfSE",title:"Maniac"},
		{url:"https://www.youtube.com/watch?v=yyWwTUIVB9U",title:"Bambous"},
		{url:"https://www.youtube.com/watch?v=D1RLCgdBuaU",title:"Suzy"},
		{url:"https://www.youtube.com/watch?v=X2gHTcKRo-I",title:"Star Scat"},
		{url:"https://www.youtube.com/watch?v=q4_NyovAYtk",title:"Dragons"},
		{url:"https://www.youtube.com/watch?v=XA-ZOLsjQoQ",title:"L'envol"},
		{url:"https://www.youtube.com/watch?v=HEAg1zgBPSc",title:"Oooh"},
		{url:"https://www.youtube.com/watch?v=8UY7FrRrGb8",title:"Violente Valse"},
		{url:"https://www.youtube.com/watch?v=ZlZ6Vf3EAlc",title:"Dramophone"},
		{url:"https://www.youtube.com/watch?v=2mkST82IHGU",title:"Cottonheads"},
		{url:"https://www.youtube.com/watch?v=BTeELC8A6-s",title:"We Can Dance"},
		{url:"https://www.youtube.com/watch?v=_sBZdSHAIZI",title:"Clash (Original Mix)"},
		{url:"https://www.youtube.com/watch?v=tY1YKHSTIi0",title:"Beatophone"},
		{url:"https://www.youtube.com/watch?v=f-vw7fYmQP0",title:"Wonderland"},
		{url:"https://www.youtube.com/watch?v=n_EjOVGaiYg",title:"Russian"},
		{url:"https://www.youtube.com/watch?v=mDJpbIYtwss",title:"Glory of Nelly"},
		{url:"https://www.youtube.com/watch?v=IKUe9cMhx2Q",title:"Queens"},
		{url:"https://www.youtube.com/watch?v=vSNXiLTIDX4",title:"Sydney"},
		{url:"https://www.youtube.com/watch?v=pSdhXbNoKxc",title:"Pirates"},
		{url:"https://www.youtube.com/watch?v=CPCtRWBWVZw",title:"Brotherswing"}			
	]}

];

module.exports = playlists;